# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.15.8
      - image: mongo:4.4.5
        environment:
          - MONGO_INITDB_ROOT_USERNAME=usagibooru
          - MONGO_INITDB_ROOT_PASSWORD=kokoro_pyonpyon
          - MONGO_INITDB_DATABASE=accounts
          - TZ=Asia/Tokyo
    environment:
      MONGO_HOST: "localhost:27017"
      MONGO_USER: "usagibooru"
      MONGO_PASS: "kokoro_pyonpyon"
      ELASTIC_HOST: "localhost:9200"
      ELASTIC_USER: ""
      ELASTIC_PASS: ""
      JWT_SECRET: "UNSAFE_SECRET_KEY_CHANGE_ME!"
      TEST_RESULTS: "/tmp/test-results"
    steps:
      - checkout
      - run:
          name: Make test result dir
          command: mkdir -p $TEST_RESULTS
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install build dependencies
          command: go mod download
      - run:
          name: Install test dependencies
          command: |
            go get -u github.com/jstemmer/go-junit-report
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Waiting for MongoDB to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 27017 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MongoDB && exit 1
      - run:
          name: Run tests
          command: |
            go test ./impl -timeout 300s -cover -coverprofile=${TEST_RESULTS}/coverage.txt -v impl/* 2>&1 | go-junit-report > ${TEST_RESULTS}/report.xml
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
      - codecov/upload:
          when: always
          file: /tmp/test-results/coverage.txt
